# ARG VARIANT=9.3
FROM gentoo/stage3:amd64-systemd-mergedusr

COPY common-gentoo.sh .

RUN emerge-rsync

ARG INSTALL_ZSH=false
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN bash common-gentoo.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" \
    && emerge --depclean \
    && rm -rf common-gentoo.sh

WORKDIR /workspace
