FROM amazonlinux:2023

RUN dnf update -y

ARG INSTALL_ZSH=false
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN curl https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.245.2/script-library/common-redhat.sh -o common-redhat.sh

# patch
RUN sed -i '/redhat-lsb-core/d' common-redhat.sh
RUN sed -i '/curl/d' common-redhat.sh
RUN sed -i '/gnupg2/d' common-redhat.sh

RUN bash common-redhat.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" \
    && dnf clean all && rm -rf common-redhat.sh

WORKDIR /workspace
