name: build ubi9 image

on:
  schedule:
    # 分 時 日 月 曜日
    - cron:  '0 13 1 * *'
  push:
    paths:
      - 'ubi9/**'
      - '!ubi9/README.md'
      - '.github/workflows/ubi9.yml'
  pull_request:
    paths:
      - 'ubi9/**'
      - '!ubi9/README.md'
      - '.github/workflows/ubi9.yml'

# write permission implies read permission.
permissions:
  # for create release tag
  contents: write
  # for push to ghcr.io registry.
  packages: write
  

jobs:
  ubi9:
    name: packaging ubi9 image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ubi-devcontainer
      REGISTRY: ghcr.io
    steps:

    - uses: actions/checkout@v4

    - name: Log in to Red Hat Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: registry.redhat.io
        username: ${{ secrets.REGISTRY_REDHAT_IO_USER }}
        password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}
    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: latest ubi9 ${{ github.sha }}
        containerfiles: |
          ./ubi9/Containerfile

    - name: Push to GitHub Container Repository
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
